/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dumbara.view;

import dumabara.controller.LoanOptionController;
import dumbara.model.LoanOptionsM;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ChanakaDe
 */
public class LoanOptions extends javax.swing.JDialog {

    /**
     * Creates new form LoanOptions
     */
    public LoanOptions(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        try {
            LoanOptionsM[] loanOptionsMs=LoanOptionController.viewLoanOption();
                l1.setText(loanOptionsMs[0].getLowest()+"");
                l2.setText(loanOptionsMs[1].getLowest()+"");
                l3.setText(loanOptionsMs[2].getLowest()+"");
                l4.setText(loanOptionsMs[3].getLowest()+"");
                l5.setText(loanOptionsMs[4].getLowest()+"");
                
                h1.setText(loanOptionsMs[0].getHighest()+"");
                h2.setText(loanOptionsMs[1].getHighest()+"");
                h3.setText(loanOptionsMs[2].getHighest()+"");
                h4.setText(loanOptionsMs[3].getHighest()+"");
                h5.setText(loanOptionsMs[4].getHighest()+"");
                
                r1.setText(loanOptionsMs[0].getRate()+"");
                r2.setText(loanOptionsMs[1].getRate()+"");
                r3.setText(loanOptionsMs[2].getRate()+"");
                r4.setText(loanOptionsMs[3].getRate()+"");
                r5.setText(loanOptionsMs[4].getRate()+"");

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(LoanOptions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        editButton = new javax.swing.JButton();
        l5 = new javax.swing.JTextField();
        h4 = new javax.swing.JTextField();
        h3 = new javax.swing.JTextField();
        l1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        r2 = new javax.swing.JTextField();
        h1 = new javax.swing.JTextField();
        l4 = new javax.swing.JTextField();
        cancelbutton = new javax.swing.JButton();
        l3 = new javax.swing.JTextField();
        r3 = new javax.swing.JTextField();
        l2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        h2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        h5 = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        r1 = new javax.swing.JTextField();
        r4 = new javax.swing.JTextField();
        r5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        id1 = new javax.swing.JTextField();
        id2 = new javax.swing.JTextField();
        id3 = new javax.swing.JTextField();
        id4 = new javax.swing.JTextField();
        id5 = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        editButton.setBackground(new java.awt.Color(204, 204, 255));
        editButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        l5.setEditable(false);
        l5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                l5FocusGained(evt);
            }
        });

        h4.setEditable(false);
        h4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        h4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                h4FocusGained(evt);
            }
        });

        h3.setEditable(false);
        h3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        h3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h3ActionPerformed(evt);
            }
        });
        h3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                h3FocusGained(evt);
            }
        });

        l1.setEditable(false);
        l1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l1ActionPerformed(evt);
            }
        });
        l1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                l1FocusGained(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Set Interest Rate");

        r2.setEditable(false);
        r2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        r2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                r2FocusGained(evt);
            }
        });

        h1.setEditable(false);
        h1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        h1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                h1FocusGained(evt);
            }
        });

        l4.setEditable(false);
        l4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                l4FocusGained(evt);
            }
        });

        cancelbutton.setBackground(new java.awt.Color(255, 153, 153));
        cancelbutton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cancelbutton.setText("Cancel");
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });

        l3.setEditable(false);
        l3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                l3FocusGained(evt);
            }
        });

        r3.setEditable(false);
        r3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        r3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                r3FocusGained(evt);
            }
        });

        l2.setEditable(false);
        l2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        l2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                l2FocusGained(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Interest Rate");

        h2.setEditable(false);
        h2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        h2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                h2FocusGained(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Lowest Value");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Highest Value");

        h5.setEditable(false);
        h5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        h5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h5ActionPerformed(evt);
            }
        });
        h5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                h5FocusGained(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(204, 204, 255));
        saveButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        r1.setEditable(false);
        r1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        r1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                r1FocusGained(evt);
            }
        });

        r4.setEditable(false);
        r4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        r4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                r4FocusGained(evt);
            }
        });

        r5.setEditable(false);
        r5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        r5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                r5FocusGained(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("RateID");

        id1.setEditable(false);
        id1.setBackground(new java.awt.Color(204, 204, 255));
        id1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id1.setText("RID1");
        id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id1ActionPerformed(evt);
            }
        });
        id1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                id1FocusGained(evt);
            }
        });

        id2.setEditable(false);
        id2.setBackground(new java.awt.Color(204, 204, 255));
        id2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id2.setText("RID2");
        id2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                id2FocusGained(evt);
            }
        });

        id3.setEditable(false);
        id3.setBackground(new java.awt.Color(204, 204, 255));
        id3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id3.setText("RID3");
        id3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                id3FocusGained(evt);
            }
        });

        id4.setEditable(false);
        id4.setBackground(new java.awt.Color(204, 204, 255));
        id4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id4.setText("RID4");
        id4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                id4FocusGained(evt);
            }
        });

        id5.setEditable(false);
        id5.setBackground(new java.awt.Color(204, 204, 255));
        id5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id5.setText("RID5");
        id5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                id5FocusGained(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(204, 204, 255));
        updateButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(updateButton)
                        .addGap(18, 18, 18)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(id4)
                            .addComponent(id3)
                            .addComponent(id2)
                            .addComponent(id1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                            .addComponent(id5))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(l1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(l3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(h5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(h4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(h3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(h1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(h2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cancelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(r4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(r3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(r1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(r2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGap(47, 47, 47))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(h1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(h2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(h3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(h4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(h5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(r1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(r2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(r3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(r4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(r5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(id2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(id3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(id4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(id5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        l1.setEditable(true);
        l2.setEditable(true);
        l3.setEditable(true);
        l4.setEditable(true);
        l5.setEditable(true);
        
        h1.setEditable(true);
        h2.setEditable(true);
        h3.setEditable(true);
        h4.setEditable(true);
        h5.setEditable(true);
        
        r1.setEditable(true);
        r2.setEditable(true);
        r3.setEditable(true);
        r4.setEditable(true);
        r5.setEditable(true);
        
    }//GEN-LAST:event_editButtonActionPerformed

    private void l1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_l1FocusGained
        l1.selectAll();
    }//GEN-LAST:event_l1FocusGained

    private void l2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_l2FocusGained
        l2.selectAll();
    }//GEN-LAST:event_l2FocusGained

    private void l3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_l3FocusGained
        l3.selectAll();
    }//GEN-LAST:event_l3FocusGained

    private void l4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_l4FocusGained
        l4.selectAll();
    }//GEN-LAST:event_l4FocusGained

    private void l5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_l5FocusGained
        l5.selectAll();
    }//GEN-LAST:event_l5FocusGained

    private void h1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_h1FocusGained
        h1.selectAll();
    }//GEN-LAST:event_h1FocusGained

    private void h2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_h2FocusGained
        h2.selectAll();
    }//GEN-LAST:event_h2FocusGained

    private void h3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_h3FocusGained
        h3.selectAll();
    }//GEN-LAST:event_h3FocusGained

    private void h4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_h4FocusGained
        h4.selectAll();
    }//GEN-LAST:event_h4FocusGained

    private void h5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_h5FocusGained
        h5.selectAll();
    }//GEN-LAST:event_h5FocusGained

    private void r1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_r1FocusGained
        r1.selectAll();
    }//GEN-LAST:event_r1FocusGained

    private void r2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_r2FocusGained
        r2.selectAll();
    }//GEN-LAST:event_r2FocusGained

    private void r3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_r3FocusGained
        r3.selectAll();
    }//GEN-LAST:event_r3FocusGained

    private void r4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_r4FocusGained
        r4.selectAll();
    }//GEN-LAST:event_r4FocusGained

    private void r5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_r5FocusGained
        r5.selectAll();
    }//GEN-LAST:event_r5FocusGained

    private void id1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_id1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_id1FocusGained

    private void id2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_id2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_id2FocusGained

    private void id3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_id3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_id3FocusGained

    private void id4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_id4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_id4FocusGained

    private void id5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_id5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_id5FocusGained

    private void id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id1ActionPerformed

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelbuttonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        ArrayList<LoanOptionsM> arrayList=new ArrayList<>();
        String id;
        double lowest;
        double highest;
        double rate;
        
        id=id1.getText();
        lowest=Double.parseDouble(l1.getText());
        highest=Double.parseDouble(h1.getText());
        rate=Double.parseDouble(r1.getText());
        
        LoanOptionsM loanOptionsM=new LoanOptionsM(id, lowest, highest, rate);
        arrayList.add(loanOptionsM);
        
        id=id2.getText();
        lowest=Double.parseDouble(l2.getText());
        highest=Double.parseDouble(h2.getText());
        rate=Double.parseDouble(r2.getText());
        
        loanOptionsM=new LoanOptionsM(id, lowest, highest, rate);
        arrayList.add(loanOptionsM);
        
        
        id=id3.getText();
        lowest=Double.parseDouble(l3.getText());
        highest=Double.parseDouble(h3.getText());
        rate=Double.parseDouble(r3.getText());
        
        loanOptionsM=new LoanOptionsM(id, lowest, highest, rate);
        arrayList.add(loanOptionsM);
        
        id=id4.getText();
        lowest=Double.parseDouble(l4.getText());
        highest=Double.parseDouble(h4.getText());
        rate=Double.parseDouble(r4.getText());
        
        loanOptionsM=new LoanOptionsM(id, lowest, highest, rate);
        arrayList.add(loanOptionsM);
        
        id=id5.getText();
        lowest=Double.parseDouble(l5.getText());
        highest=Double.parseDouble(h5.getText());
        rate=Double.parseDouble(r5.getText());
        
        loanOptionsM=new LoanOptionsM(id, lowest, highest, rate);
        arrayList.add(loanOptionsM);
        try {
            int res=LoanOptionController.addLoanOption(arrayList);
            if(res>0){
                JOptionPane.showMessageDialog(rootPane, "Added ");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Error ");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(LoanOptions.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void h5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h5ActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        ArrayList<LoanOptionsM> arrayList=new ArrayList<>();
        String id;
        double lowest;
        double highest;
        double rate;
        
        id=id1.getText();
        lowest=Double.parseDouble(l1.getText());
        highest=Double.parseDouble(h1.getText());
        rate=Double.parseDouble(r1.getText());
        
        LoanOptionsM loanOptionsM=new LoanOptionsM(id, lowest, highest, rate);
        arrayList.add(loanOptionsM);
        
        id=id2.getText();
        lowest=Double.parseDouble(l2.getText());
        highest=Double.parseDouble(h2.getText());
        rate=Double.parseDouble(r2.getText());
        
        loanOptionsM=new LoanOptionsM(id, lowest, highest, rate);
        arrayList.add(loanOptionsM);
        
        
        id=id3.getText();
        lowest=Double.parseDouble(l3.getText());
        highest=Double.parseDouble(h3.getText());
        rate=Double.parseDouble(r3.getText());
        
        loanOptionsM=new LoanOptionsM(id, lowest, highest, rate);
        arrayList.add(loanOptionsM);
        
        id=id4.getText();
        lowest=Double.parseDouble(l4.getText());
        highest=Double.parseDouble(h4.getText());
        rate=Double.parseDouble(r4.getText());
        
        loanOptionsM=new LoanOptionsM(id, lowest, highest, rate);
        arrayList.add(loanOptionsM);
        
        id=id5.getText();
        lowest=Double.parseDouble(l5.getText());
        highest=Double.parseDouble(h5.getText());
        rate=Double.parseDouble(r5.getText());
        
        loanOptionsM=new LoanOptionsM(id, lowest, highest, rate);
        arrayList.add(loanOptionsM);
        try {
            int updateLoanOption = LoanOptionController.updateLoanOption(arrayList);
            if (updateLoanOption>0) {{
                JOptionPane.showMessageDialog(rootPane, "Updated ...");
            }
                
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(LoanOptions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void l1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l1ActionPerformed

    private void h3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoanOptions dialog = new LoanOptions(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbutton;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField h1;
    private javax.swing.JTextField h2;
    private javax.swing.JTextField h3;
    private javax.swing.JTextField h4;
    private javax.swing.JTextField h5;
    private javax.swing.JTextField id1;
    private javax.swing.JTextField id2;
    private javax.swing.JTextField id3;
    private javax.swing.JTextField id4;
    private javax.swing.JTextField id5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField l1;
    private javax.swing.JTextField l2;
    private javax.swing.JTextField l3;
    private javax.swing.JTextField l4;
    private javax.swing.JTextField l5;
    private javax.swing.JTextField r1;
    private javax.swing.JTextField r2;
    private javax.swing.JTextField r3;
    private javax.swing.JTextField r4;
    private javax.swing.JTextField r5;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
