/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dumbara.view;

import dumabara.controller.EmployeeController;
import dumabara.controller.LoanController;
import dumabara.controller.LoanOptionController;
import dumabara.controller.LoanOptionSetcountController;
import dumabara.controller.LoanSettleController;
import dumabara.controller.ReportController;
import dumbara.model.Employee;
import dumbara.model.Loan;
import dumbara.model.LoanOptionSetCount;
import dumbara.model.LoanOptionsM;
import dumbara.model.LoanSettle;
import java.io.IOException;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chanu1993
 */
public class New_Loan extends javax.swing.JFrame {

    ArrayList<Object[]> rowList;
    ArrayList<Object[]> rowList1;
    private  int draggingX;
    private  int draggingY;
    private int x;
    private int y;
    /**
     * Creates new form New_Loan
     */
    public New_Loan() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(2);
        setResizable(false);
        x = getX();
        y = getY();
        try {
            loadIdText.setText(generateID());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(New_Loan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            fillEmployeeCombo();
        } catch (ClassNotFoundException | SQLException | IOException ex) {
            Logger.getLogger(New_Loan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            Loan[] loan=LoanController.viewLoan();
            DefaultTableModel dtm=(DefaultTableModel) loanTable.getModel();
            for (Loan loan1 : loan) {
                Object[] rows={loan1.getLoanID(),loan1.getEmpID(),loan1.getLongAmount(),loan1.getLoanTerm(),loan1.getInterestRate(),loan1.getMonthlyPayment(),loan1.getDueAmount()};
                dtm.addRow(rows);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewLoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        rowList=new ArrayList<>();
        for(int i=0;i<loanTable.getRowCount();i++){
            Object[] row={loanTable.getValueAt(i, 0),loanTable.getValueAt(i, 1),loanTable.getValueAt(i, 2),loanTable.getValueAt(i, 3),loanTable.getValueAt(i, 4),loanTable.getValueAt(i, 5)};
            rowList.add(row);
        }
        try {
            LoanSettle [] ls=LoanSettleController.viewLoanSettle();
            DefaultTableModel dtm=(DefaultTableModel) loanHistoryTable.getModel();
            for (LoanSettle loanSettle : ls) {
                Object[] rows={loanSettle.getLoanSettleID(),loanSettle.getLoanID(),loanSettle.getPayment(),loanSettle.getLoanAmount(),loanSettle.getDuePayment(),loanSettle.getPaymentDate()};
                dtm.addRow(rows);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PaymentHistory.class.getName()).log(Level.SEVERE, null, ex);
        }
        rowList1=new ArrayList<>();
        for(int i=0;i<loanHistoryTable.getRowCount();i++){
            Object[] row={loanHistoryTable.getValueAt(i, 0),loanHistoryTable.getValueAt(i, 1),loanHistoryTable.getValueAt(i, 2),loanHistoryTable.getValueAt(i, 3),loanHistoryTable.getValueAt(i, 4),loanHistoryTable.getValueAt(i, 5),};
            rowList1.add(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        loanIdText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        loanTable = new javax.swing.JTable();
        empIdText = new javax.swing.JTextField();
        removeLoan = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        settleButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        monthlyPaymentText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        loanTermYearText = new javax.swing.JTextField();
        loanAmountText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        employeeCombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        interestRateText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        loadIdText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        loanTermMonthText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        amountLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        contactNotextA = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        civilStatusTextA = new javax.swing.JTextField();
        nicTextA = new javax.swing.JTextField();
        salaryTextA = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        imgLable = new javax.swing.JLabel();
        nameTextA = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        loanCountText = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        civilStatusTextA2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        loanHistoryTable = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBackground(java.awt.Color.white);
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 4));

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 2));

        loanIdText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loanIdText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loanIdTextFocusGained(evt);
            }
        });
        loanIdText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                loanIdTextKeyReleased(evt);
            }
        });

        loanTable.setForeground(new java.awt.Color(0, 0, 102));
        loanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LoanID", "EmpID", "Amount", "LoanTerm", "InterestRate", "MonthlyPayment"
            }
        ));
        loanTable.setRowHeight(30);
        loanTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loanTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(loanTable);

        empIdText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        empIdText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                empIdTextFocusGained(evt);
            }
        });
        empIdText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                empIdTextKeyReleased(evt);
            }
        });

        removeLoan.setBackground(new java.awt.Color(255, 204, 204));
        removeLoan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        removeLoan.setText("Remove Loan");
        removeLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLoanActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Loan ID :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Emp ID :");

        settleButton.setBackground(new java.awt.Color(204, 204, 255));
        settleButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        settleButton.setText("Settle Payments");
        settleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settleButtonMouseClicked(evt);
            }
        });
        settleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settleButtonActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 204, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton7.setText("Print Loan Policy");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loanIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(settleButton)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(removeLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(loanIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(empIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 101, 217), 2));

        monthlyPaymentText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        monthlyPaymentText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                monthlyPaymentTextFocusGained(evt);
            }
        });
        monthlyPaymentText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                monthlyPaymentTextKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Employee :");

        loanTermYearText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loanTermYearText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanTermYearTextActionPerformed(evt);
            }
        });
        loanTermYearText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loanTermYearTextFocusGained(evt);
            }
        });
        loanTermYearText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                loanTermYearTextKeyReleased(evt);
            }
        });

        loanAmountText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loanAmountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanAmountTextActionPerformed(evt);
            }
        });
        loanAmountText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loanAmountTextFocusGained(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Interest Rate :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Loan Term :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Monthly Payment :");

        employeeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeComboActionPerformed(evt);
            }
        });
        employeeCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                employeeComboFocusGained(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Loan Amount :");

        addButton.setBackground(new java.awt.Color(204, 204, 255));
        addButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addButton.setText("Add");
        addButton.setEnabled(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        interestRateText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        interestRateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interestRateTextActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Loan ID :");

        loadIdText.setEditable(false);
        loadIdText.setBackground(new java.awt.Color(255, 204, 255));
        loadIdText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("yrs or");

        loanTermMonthText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loanTermMonthText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanTermMonthTextActionPerformed(evt);
            }
        });
        loanTermMonthText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loanTermMonthTextFocusGained(evt);
            }
        });
        loanTermMonthText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                loanTermMonthTextKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("months");

        resetButton.setBackground(new java.awt.Color(204, 204, 255));
        resetButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        amountLabel.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(90, 90, 90)
                                .addComponent(employeeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 35, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loanAmountText)
                                    .addComponent(interestRateText)
                                    .addComponent(monthlyPaymentText)
                                    .addComponent(loadIdText)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(loanTermYearText, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(loanTermMonthText, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(amountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(resetButton)
                        .addGap(32, 32, 32))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(employeeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(loadIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(loanAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(loanTermMonthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(loanTermYearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(interestRateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(monthlyPaymentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Loan Manager");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 0, 102));
        jLabel17.setText("Loan Information");

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));

        contactNotextA.setEditable(false);
        contactNotextA.setBackground(java.awt.Color.white);
        contactNotextA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        contactNotextA.setForeground(new java.awt.Color(0, 0, 102));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("NIC :");

        civilStatusTextA.setEditable(false);
        civilStatusTextA.setBackground(java.awt.Color.white);
        civilStatusTextA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        civilStatusTextA.setForeground(new java.awt.Color(0, 0, 102));

        nicTextA.setEditable(false);
        nicTextA.setBackground(java.awt.Color.white);
        nicTextA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nicTextA.setForeground(new java.awt.Color(0, 0, 102));

        salaryTextA.setEditable(false);
        salaryTextA.setBackground(java.awt.Color.white);
        salaryTextA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        salaryTextA.setForeground(new java.awt.Color(0, 0, 102));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Salary :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Name :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Contact No :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Civil Status :");

        nameTextA.setEditable(false);
        nameTextA.setBackground(java.awt.Color.white);
        nameTextA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nameTextA.setForeground(new java.awt.Color(0, 0, 102));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Loan Count :");

        loanCountText.setEditable(false);
        loanCountText.setBackground(java.awt.Color.white);
        loanCountText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        loanCountText.setForeground(new java.awt.Color(204, 0, 0));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("OnHand Salary :");

        civilStatusTextA2.setEditable(false);
        civilStatusTextA2.setBackground(java.awt.Color.white);
        civilStatusTextA2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        civilStatusTextA2.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameTextA)
                            .addComponent(nicTextA)
                            .addComponent(contactNotextA)
                            .addComponent(salaryTextA)
                            .addComponent(civilStatusTextA, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(imgLable, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loanCountText, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(civilStatusTextA2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(nameTextA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(nicTextA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(contactNotextA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(salaryTextA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(civilStatusTextA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgLable, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(loanCountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(civilStatusTextA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 0, 102));
        jLabel18.setText("Employee Information");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 0, 102));
        jLabel19.setText("Loan Options");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2));

        loanHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SettleID", "LoanID", "Payment", "LoanAmount", "DuePayment", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        loanHistoryTable.setRowHeight(25);
        jScrollPane2.setViewportView(loanHistoryTable);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 0, 102));
        jLabel20.setText("Loan Settle Information");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Total Settlements :");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(153, 153, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setText("View Loans");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setText("By Employee");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setText("History by Emp");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 0, 102));
        jLabel22.setText("Loan Details by Graphs");

        jButton1.setBackground(new java.awt.Color(204, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(77, 77, 77))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loanTermYearTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanTermYearTextActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_loanTermYearTextActionPerformed

    private void loanTermYearTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loanTermYearTextFocusGained
        // TODO add your handling code here:
        loanTermYearText.selectAll();
    }//GEN-LAST:event_loanTermYearTextFocusGained

    private void loanTermYearTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loanTermYearTextKeyReleased
        // TODO add your handling code here:
        if(loanTermYearText.getText().equals("")){
            loanTermYearText.setText("0");
        }
        double months=12*Double.parseDouble(loanTermYearText.getText());
        loanTermMonthText.setText(months+"");
    }//GEN-LAST:event_loanTermYearTextKeyReleased

    private void loanAmountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanAmountTextActionPerformed
        double amount=Double.parseDouble(loanAmountText.getText());
        try {
            LoanOptionsM[] loanOptionsMs = LoanOptionController.viewLoanOption();
            for (int i = 0; i < loanOptionsMs.length; i++) {
                LoanOptionsM loanOptionsM = loanOptionsMs[i];
                if (loanOptionsM.isRelevantOption(amount)) {
                    interestRateText.setText(loanOptionsM.getRate()+"");
                    break;
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(New_Loan.class.getName()).log(Level.SEVERE, null, ex);
        }
        loanTermMonthText.requestFocus();
    }//GEN-LAST:event_loanAmountTextActionPerformed

    private void loanAmountTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loanAmountTextFocusGained
        // TODO add your handling code here:
        loanAmountText.selectAll();
    }//GEN-LAST:event_loanAmountTextFocusGained

    private void employeeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeComboActionPerformed
        // TODO add your handling code here:
        String empID=((Employee)employeeCombo.getSelectedItem()).getEmpID();
        double salary=0;
        
            try {
                Employee [] employees=EmployeeController.viewAllEmployeebyID(empID);
                ImageIcon img=EmployeeController.viewEmployeeImg(empID);
                for (Employee employee : employees) {
                    nameTextA.setText(employee.getName());
                    nicTextA.setText(employee.getNic());
                    contactNotextA.setText(employee.getContactNo());
                    salaryTextA.setText(employee.getSalary()+"");
                    System.out.println(employee.getSalary());
                    civilStatusTextA.setText(employee.getCivilStatus());
                     salary = employee.getSalary();
                    amountLabel.setText("Maximum Loan Amount : "+salary*5);
                    //status bar about Employee  Salary
                  
                    
                }
                imgLable.setIcon(img);
                
                //new addings to find loan count    **************************
                try {
                    LoanOptionSetCount[] loanOptionsMs = LoanOptionSetcountController.viewLoanOptionSetCounts();
                    for (int i = 0; i < loanOptionsMs.length; i++) {
                        LoanOptionSetCount loanOptionsM = loanOptionsMs[i];
                        if (loanOptionsM.isRelevantOption(salary)) {
                            loanCountText.setText(loanOptionsM.getCount() + "");
                            break;
                        }
                    }
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(New_Loan.class.getName()).log(Level.SEVERE, null, ex);
                }
                //
                
            } catch (ClassNotFoundException | IOException | SQLException ex) {
                Logger.getLogger(New_Loan.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            //Add suitable loans for this employee to the table
            
        try {
            Loan[] loan = LoanController.viewLoanbyID(empID);
            DefaultTableModel dtm = (DefaultTableModel) loanTable.getModel();
            dtm.setRowCount(0);
            for (Loan loan1 : loan) {
                Object[] rows = {loan1.getLoanID(), loan1.getEmpID(), loan1.getLongAmount(), loan1.getLoanTerm(), loan1.getInterestRate(), loan1.getMonthlyPayment(), loan1.getDueAmount()};
                dtm.addRow(rows);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewLoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_employeeComboActionPerformed

    private void employeeComboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_employeeComboFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeComboFocusGained

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String empID=((Employee)employeeCombo.getSelectedItem()).getEmpID();
        String loadID=loadIdText.getText();
        String loanAmount=loanAmountText.getText();
        String loanTerm=loanTermMonthText.getText();
        String interestRate=interestRateText.getText();
        String monthlyPayment=monthlyPaymentText.getText();
        Loan loan=new Loan(empID, loadID, loanAmount, loanTerm, interestRate, monthlyPayment,"Full Amount");
        try {
            int res=LoanController.addLoan(loan);
            if(res>0){
                JOptionPane.showMessageDialog(this, "Added");
            }else{
                JOptionPane.showMessageDialog(this, "Error");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(New_Loan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //reload the loan table
        try {
            Loan[] loan11=LoanController.viewLoan();
            DefaultTableModel dtm=(DefaultTableModel) loanTable.getModel();
            for (Loan loan1 : loan11) {
                Object[] rows={loan1.getLoanID(),loan1.getEmpID(),loan1.getLongAmount(),loan1.getLoanTerm(),loan1.getInterestRate(),loan1.getMonthlyPayment(),loan1.getDueAmount()};
                dtm.addRow(rows);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewLoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        resetButton.requestFocus();
    }//GEN-LAST:event_addButtonActionPerformed

    private void interestRateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interestRateTextActionPerformed
        // TODO add your handling code here:
        double value=(Double.parseDouble(loanAmountText.getText())*Double.parseDouble(interestRateText.getText())/100)/12;
        double finals=value+(Double.parseDouble(loanAmountText.getText())/(Double.parseDouble(loanTermMonthText.getText())));
        //double lastvalue=Math.round(finals);

        NumberFormat nm = NumberFormat.getCurrencyInstance();
        String format = nm.format(finals);
        monthlyPaymentText.setText(format.substring(1));

        addButton.requestFocus();
    }//GEN-LAST:event_interestRateTextActionPerformed

    private void loanTermMonthTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanTermMonthTextActionPerformed
        // TODO add your handling code here:
        interestRateText.requestFocus();
    }//GEN-LAST:event_loanTermMonthTextActionPerformed

    private void loanTermMonthTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loanTermMonthTextFocusGained
        // TODO add your handling code here:
        loanTermMonthText.selectAll();
    }//GEN-LAST:event_loanTermMonthTextFocusGained

    private void loanTermMonthTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loanTermMonthTextKeyReleased
        // TODO add your handling code here:
        if(loanTermMonthText.getText().equals("")){
            loanTermMonthText.setText("0");
        }
        double years=(Double.parseDouble(loanTermMonthText.getText()))/12;
        years = (int)(years*100);
        loanTermYearText.setText(years/100+"");
    }//GEN-LAST:event_loanTermMonthTextKeyReleased

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        try {
            // TODO add your handling code here:
            loadIdText.setText(generateID());
            loanAmountText.setText("");
            loanTermYearText.setText("");
            loanTermMonthText.setText("");
            interestRateText.setText("");
            monthlyPaymentText.setText("");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(New_Loan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_resetButtonActionPerformed

    private void loanIdTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loanIdTextFocusGained
        // TODO add your handling code here:
        loanIdText.selectAll();
    }//GEN-LAST:event_loanIdTextFocusGained

    private void loanIdTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loanIdTextKeyReleased
        String loanId=loanIdText.getText();
        DefaultTableModel dtm=(DefaultTableModel) loanTable.getModel();
        dtm.setRowCount(0);
        for(Object[] row:rowList){
            if(row[0].toString().contains(loanId)){
                dtm.addRow(row);
            }
        }
    }//GEN-LAST:event_loanIdTextKeyReleased

    private void empIdTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empIdTextFocusGained
        // TODO add your handling code here:
        empIdText.selectAll();
    }//GEN-LAST:event_empIdTextFocusGained

    private void empIdTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empIdTextKeyReleased
        String empId=empIdText.getText();
        DefaultTableModel dtm=(DefaultTableModel) loanTable.getModel();
        dtm.setRowCount(0);
        for (Object[] objects : rowList) {
            if(objects[1].toString().contains(empId)){
                dtm.addRow(objects);
            }
        }

    }//GEN-LAST:event_empIdTextKeyReleased

    private void removeLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeLoanActionPerformed
        if (loanTable.getSelectedRowCount()==0) {
            JOptionPane.showMessageDialog(rootPane, "Error");
        }else{
            int row=loanTable.getSelectedRow();
        String LoanID=(String) loanTable.getModel().getValueAt(row, 0);
        try {
            int res=LoanController.deleteLoan(LoanID);
            if(res>0){
                JOptionPane.showMessageDialog(this, "Deleted");
                refresh();
            }else{
                JOptionPane.showMessageDialog(this, "Error");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewLoan.class.getName()).log(Level.SEVERE, null, ex);
        }  
        }


    }//GEN-LAST:event_removeLoanActionPerformed

    private void settleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settleButtonMouseClicked
        if (loanTable.getSelectedRowCount()==0) {
            JOptionPane.showMessageDialog(rootPane, "Error");
        }else{
        x=evt.getXOnScreen();
        y=evt.getYOnScreen();

        int row=loanTable.getSelectedRow();
        String loanAmount=(String) loanTable.getModel().getValueAt(row, 2);
        String monthlyPayment=(String) loanTable.getModel().getValueAt(row, 5);
        String loanID=(String) loanTable.getValueAt(row, 0);

        Loan loan=new Loan(loanAmount,monthlyPayment,loanID);

        new SettlePayment(this, true,x-100,y-100,loan).setVisible(true);
        }
 
    }//GEN-LAST:event_settleButtonMouseClicked

    private void settleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settleButtonActionPerformed

    }//GEN-LAST:event_settleButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Chart1.loanInfo();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Chart1.byEmployee();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (loanTable.getSelectedRowCount()==0) {
            JOptionPane.showMessageDialog(rootPane, "Error");
        }else{
        int row=loanTable.getSelectedRow();
        String empID=(String) loanTable.getModel().getValueAt(row, 0);
        Chart1.paymentHistorybyEmp(empID); 
        }

        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void monthlyPaymentTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monthlyPaymentTextKeyReleased
        String id = loadIdText.getText();
        String amount = loanAmountText.getText();
        String rate = interestRateText.getText();
        String payment = monthlyPaymentText.getText();
        String month = loanTermMonthText.getText();
        if (!id.equals("")&&!amount.equals("")&&!rate.equals("")&&!payment.equals("")&&!month.equals("")) {
            addButton.setEnabled(true);
        }
    }//GEN-LAST:event_monthlyPaymentTextKeyReleased

    private void monthlyPaymentTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthlyPaymentTextFocusGained
        monthlyPaymentText.selectAll();
    }//GEN-LAST:event_monthlyPaymentTextFocusGained

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       int row=loanTable.getSelectedRow();
     if(loanTable.getSelectedRowCount()==0){
         JOptionPane.showMessageDialog(rootPane, "Error");
     }else{
            try {
            Map<String, Object> params = new HashMap<>();
            params.put("LoanID", loanTable.getValueAt(row, 0));
            params.put("EmpID", loanTable.getValueAt(row, 1));
            params.put("Amount", loanTable.getValueAt(row, 2));
            params.put("LoanTerm", loanTable.getValueAt(row, 3));
            params.put("InterestRate", loanTable.getValueAt(row, 4));
            params.put("MonthlyPayment", loanTable.getValueAt(row, 5));
            //JRTableModelDataSource ds = new JRTableModelDataSource(loanTable.getModel());

            ReportController.viewReport(params, "./src/dumbara/reports/policy.jrxml");

        } catch (Exception ex) {
            ex.printStackTrace();
        }  
     }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        draggingX = evt.getXOnScreen();
        draggingY = evt.getYOnScreen();
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        
        int nx = evt.getXOnScreen() - draggingX ;
        int ny =   evt.getYOnScreen() - draggingY;
        
        draggingX = evt.getXOnScreen();
        draggingY = evt.getYOnScreen();
        x += nx;
        y += ny;
        setLocation(x, y);
        
    }//GEN-LAST:event_jPanel5MouseDragged

    private void loanTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanTableMouseClicked
        //get suitable loan settle details in the table
        int row = loanTable.getSelectedRow();
        String loanID = loanTable.getModel().getValueAt(row, 0).toString();

        try {
            LoanSettle[] ls = LoanSettleController.viewLoanSettlebyEmp(loanID);
            DefaultTableModel dtm = (DefaultTableModel) loanHistoryTable.getModel();
            dtm.setRowCount(0);
            for (LoanSettle loanSettle : ls) {
                Object[] rows = {loanSettle.getLoanSettleID(), loanSettle.getLoanID(), loanSettle.getPayment(), loanSettle.getLoanAmount(), loanSettle.getDuePayment(), loanSettle.getPaymentDate()};
                dtm.addRow(rows);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PaymentHistory.class.getName()).log(Level.SEVERE, null, ex);
        }
        //get the sum of all the settlements
        double sum=0;
        for (int i = 0; i < loanHistoryTable.getRowCount(); i++) {
            sum+=Double.parseDouble(loanHistoryTable.getValueAt(i, 2).toString());
        }
        jTextField1.setText(sum+"");
        // get on hand salary
        double onHand=Double.parseDouble(salaryTextA.getText())-sum;
        civilStatusTextA2.setText(onHand+"");
    }//GEN-LAST:event_loanTableMouseClicked

    public void refresh(){

        try {
            Loan[] loan=LoanController.viewLoan();
            DefaultTableModel dtm=(DefaultTableModel) loanTable.getModel();
            dtm.setRowCount(0);
            for (Loan loan1 : loan) {
                Object[] rows={loan1.getLoanID(),loan1.getEmpID(),loan1.getLongAmount(),loan1.getLoanTerm(),loan1.getInterestRate(),loan1.getMonthlyPayment(),loan1.getDueAmount()};
                dtm.addRow(rows);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewLoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_Loan().setVisible(true);
            }
        });
    }
    private void fillEmployeeCombo() throws ClassNotFoundException, SQLException, IOException{
       Employee[] employee=EmployeeController.viewAllEmployee();
        for (Employee employee1 : employee) {
            employeeCombo.addItem(employee1);
        }
    }
    private String generateID() throws ClassNotFoundException, SQLException{
        String loanID=LoanController.getLastID();
        if(loanID==null){
            return "LN0001";
        }else{
            int num=Integer.parseInt(loanID.substring(2));
            num++;
            if(num<10){
                return "LN000"+num;
            }else if(num<100){
                return "LN00"+num;
            }else if(num<1000){
                return "LN0"+num;
            }else{
                return "LN"+num;
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JTextField civilStatusTextA;
    private javax.swing.JTextField civilStatusTextA2;
    private javax.swing.JTextField contactNotextA;
    private javax.swing.JTextField empIdText;
    private javax.swing.JComboBox employeeCombo;
    private javax.swing.JLabel imgLable;
    private javax.swing.JTextField interestRateText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField loadIdText;
    private javax.swing.JTextField loanAmountText;
    private javax.swing.JTextField loanCountText;
    private javax.swing.JTable loanHistoryTable;
    private javax.swing.JTextField loanIdText;
    private javax.swing.JTable loanTable;
    private javax.swing.JTextField loanTermMonthText;
    private javax.swing.JTextField loanTermYearText;
    private javax.swing.JTextField monthlyPaymentText;
    private javax.swing.JTextField nameTextA;
    private javax.swing.JTextField nicTextA;
    private javax.swing.JButton removeLoan;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField salaryTextA;
    private javax.swing.JButton settleButton;
    // End of variables declaration//GEN-END:variables
}
