/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dumbara.view;

import dumabara.controller.EmptyBottleController;
import dumabara.controller.GoodRecievenoteController;
import dumabara.controller.ReportController;
import dumabara.controller.SupplierController;
import dumabara.controller.SupplierOrderController;
import dumabara.controller.SupplierOrderDetailController;
import dumbara.model.EmptyBottle;
import dumbara.model.GoodRecieveNote;
import dumbara.model.Supplier;
import dumbara.model.SupplierOrder;
import dumbara.model.SupplierOrderDetail;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;

/**
 *
 * @author ChanakaDe
 */
public class NewGRN extends javax.swing.JDialog {
 private boolean b = false;
    /**
     * Creates new form NewGRN
     */
    public NewGRN(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fillSupplierCombo();
        b = true;
        try {
            grnText.setText(generateID());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(NewGRN.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            EmptyBottle[] emptyBottles=EmptyBottleController.viewEmptyBottles();
            DefaultTableModel dtm = (DefaultTableModel) viewTable.getModel();
            for (EmptyBottle emptyBottle : emptyBottles) {
                Object[] row={emptyBottle.getBottleID(),emptyBottle.getBottleVolume(),emptyBottle.getQty()};
                dtm.addRow(row);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(NewGRN.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            
            setLocationRelativeTo(null);
            idText.setText(generateID1());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(NewGRN.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        qtyText = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        volumeText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        resetButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        orderIDCombo = new javax.swing.JComboBox();
        grnText = new javax.swing.JTextField();
        orderDateText = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        supplierCombo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grnTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        RecievedDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        resetText = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(java.awt.Color.white);

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        qtyText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyTextActionPerformed(evt);
            }
        });
        qtyText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                qtyTextFocusGained(evt);
            }
        });
        qtyText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyTextKeyReleased(evt);
            }
        });

        addButton.setBackground(new java.awt.Color(102, 109, 146));
        addButton.setText("Add");
        addButton.setEnabled(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel8.setText("Quantity :");

        volumeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeTextActionPerformed(evt);
            }
        });
        volumeText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                volumeTextFocusGained(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel9.setText("Bottle ID :");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel10.setText("Volume :");

        cancelButton.setBackground(new java.awt.Color(240, 73, 132));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel11.setText("Add New Bottle");

        idText.setEditable(false);
        idText.setBackground(new java.awt.Color(255, 204, 255));
        idText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        idText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextActionPerformed(evt);
            }
        });

        resetButton.setBackground(new java.awt.Color(102, 109, 146));
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(37, 37, 37)
                                .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(volumeText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qtyText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volumeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));

        orderIDCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderIDComboActionPerformed(evt);
            }
        });

        grnText.setEditable(false);
        grnText.setBackground(new java.awt.Color(255, 204, 255));
        grnText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        orderDateText.setEditable(false);
        orderDateText.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        jButton4.setBackground(new java.awt.Color(240, 73, 132));
        jButton4.setText("Cancel");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("SupplierOrder ID :");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel4.setText("Supplier :");

        jButton3.setBackground(new java.awt.Color(102, 109, 146));
        jButton3.setText("Print GRN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        supplierCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierComboActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel6.setText("GRN ID :");

        jButton2.setBackground(new java.awt.Color(102, 109, 146));
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel3.setText("Ordered Date :");

        grnTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Volume", "OrderedQty", "RecievedQty", "Varience"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grnTable.setRowHeight(30);
        grnTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                grnTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(grnTable);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel5.setText("Good Recieved Date :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Update Stock / GRN");

        resetText.setBackground(new java.awt.Color(102, 109, 146));
        resetText.setText("Reset");
        resetText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(resetText, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(grnText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(supplierCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(orderIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(36, 36, 36)
                                                .addComponent(orderDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RecievedDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(1, 1, 1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(grnText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(orderIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(supplierCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(orderDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(RecievedDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 2));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setText("Stock Details");

        viewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bottle ID", "Volume", "Qty"
            }
        ));
        viewTable.setRowHeight(25);
        jScrollPane2.setViewportView(viewTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(91, 91, 91)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderIDComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderIDComboActionPerformed

        if (b) {
            String id = orderIDCombo.getSelectedItem().toString();
            DefaultTableModel dtm = (DefaultTableModel) grnTable.getModel();
            try {
                String date = SupplierOrderController.getOrderDate(id);
                orderDateText.setText(date);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(NewGRN.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                SupplierOrderDetail[] supplierOrderDetails=SupplierOrderDetailController.viewAll(id);
                dtm.setRowCount(0);
                for (SupplierOrderDetail supplierOrderDetail : supplierOrderDetails) {
                    Object[] row={supplierOrderDetail.getBottleID(),supplierOrderDetail.getBottleVolume(),supplierOrderDetail.getBottleQty()};
                    dtm.addRow(row);
                }
            } catch (    ClassNotFoundException | SQLException ex) {
                Logger.getLogger(NewGRN.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_orderIDComboActionPerformed

    private void supplierComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierComboActionPerformed
        b = false;
        try {
            String id = supplierCombo.getSelectedItem().toString().split("-")[0];
            SupplierOrder[] supplierOrder = SupplierOrderController.getAllOrders(id);
            orderIDCombo.removeAllItems();
            for (SupplierOrder supplierOrder1 : supplierOrder) {
                orderIDCombo.addItem(supplierOrder1.getSupplierOrderID());
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(NewGRN.class.getName()).log(Level.SEVERE, null, ex);
        }
        b = true;
        System.out.println();
    }//GEN-LAST:event_supplierComboActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String id1;
       String volume1;
       String oQty1;
       String rQty1;
       String varience1;
       
       int row1=grnTable.getSelectedRow();
//        for (int i = 0; i < grnTable.getRowCount(); i++){
//            id1=grnTable.getValueAt(row1, 0).toString();
//            volume1=grnTable.getValueAt(row1, 1).toString();
//            oQty1=grnTable.getValueAt(row1, 2).toString();
//            rQty1=grnTable.getValueAt(row1, 3).toString();
//            varience1=grnTable.getValueAt(row1, 4).toString();
//        }
        try {        
            ArrayList<GoodRecieveNote> goodRecieveNotes=new ArrayList<>();
            String grnID=grnText.getText();
            String orderID=orderIDCombo.getSelectedItem().toString();
            String date=RecievedDatePicker.getDate().toString();
            for (int i = 0; i < grnTable.getRowCount(); i++) {
                String id=grnTable.getModel().getValueAt(i, 0).toString();
                String volume=grnTable.getModel().getValueAt(i, 1).toString();
                String oQty=grnTable.getModel().getValueAt(i, 2).toString();
                String rQty=grnTable.getModel().getValueAt(i, 3).toString();
                String varience=grnTable.getModel().getValueAt(i, 4).toString();

                GoodRecieveNote goodRecievedNote=new GoodRecieveNote(grnID, id, date, orderID, volume, oQty, rQty, varience);
                goodRecieveNotes.add(goodRecievedNote);
            }
            int res=GoodRecievenoteController. addGRN(goodRecieveNotes);
            if(res>0){
                JOptionPane.showMessageDialog(this, "Added");
                
            }else{
                JOptionPane.showMessageDialog(this, "Error");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(NewGRN.class.getName()).log(Level.SEVERE, null, ex);
        } 

        //////////////////add to the update statements... bla blaaaa
        for (int i = 0; i < grnTable.getRowCount(); i++) {
            String id=(String) grnTable.getModel().getValueAt(i, 0);
            int qty= Integer.parseInt(grnTable.getModel().getValueAt(i, 3).toString());
            EmptyBottle emptyBottle=new EmptyBottle(id, qty);
            try {
                int res=EmptyBottleController.updateBottles(emptyBottle);
                if(res>0){
                    JOptionPane.showMessageDialog(this, "Added "+qty+" to "+id);
                }else{
                    JOptionPane.showMessageDialog(this, "Error adding "+id);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(NewGRN.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        //////////////////////////////update table again
        try {
            
            EmptyBottle[] emptyBottles=EmptyBottleController.viewEmptyBottles();
            DefaultTableModel dtm = (DefaultTableModel) viewTable.getModel();
            dtm.setRowCount(0);
            for (EmptyBottle emptyBottle : emptyBottles) {
                Object[] row={emptyBottle.getBottleID(),emptyBottle.getBottleVolume(),emptyBottle.getQty()};
                dtm.addRow(row);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(NewGRN.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String orderID=orderIDCombo.getSelectedItem().toString();
        try{
            int res=SupplierOrderController.updateSupplierOrder(orderID);
        }catch(ClassNotFoundException | SQLException ex){
            System.out.println("Updating Error");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void grnTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_grnTableKeyReleased
        int row=grnTable.getSelectedRow();
        int orderedQty=Integer.parseInt(grnTable.getModel().getValueAt(row, 2).toString());
        int recievedQty=Integer.parseInt(grnTable.getModel().getValueAt(row, 3).toString());
        if (recievedQty>orderedQty) {
            JOptionPane.showMessageDialog(rootPane, "Invalid Amount");
        }else{
        int varience=orderedQty-recievedQty;
        System.out.println(varience);
        grnTable.getModel().setValueAt(varience, row, 4);  
        }

    }//GEN-LAST:event_grnTableKeyReleased

    private void qtyTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyTextActionPerformed
        addButton.requestFocus();
    }//GEN-LAST:event_qtyTextActionPerformed

    private void qtyTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qtyTextFocusGained
        qtyText.selectAll();
    }//GEN-LAST:event_qtyTextFocusGained

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String id=idText.getText();
        String volime=volumeText.getText();
        int qty=Integer.parseInt(qtyText.getText());

        EmptyBottle emptyBottle=new EmptyBottle(id, volime, qty);
        try {
            int res=EmptyBottleController.addBottles(emptyBottle);
            if(res>0){
                JOptionPane.showMessageDialog(this, "Added "+id);
            }else{
                JOptionPane.showMessageDialog(this, "Error adding "+id);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(NewGRN.class.getName()).log(Level.SEVERE, null, ex);
        }
        resetButton.requestFocus();
    }//GEN-LAST:event_addButtonActionPerformed

    private void volumeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeTextActionPerformed
        qtyText.requestFocus();
    }//GEN-LAST:event_volumeTextActionPerformed

    private void volumeTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_volumeTextFocusGained
        volumeText.selectAll();
    }//GEN-LAST:event_volumeTextFocusGained

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void idTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextActionPerformed
        volumeText.requestFocus();
    }//GEN-LAST:event_idTextActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        volumeText.setText("");
        qtyText.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void resetTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetTextActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Map<String, Object> params = new HashMap<>();
            params.put("GRNID",grnText.getText() );
            params.put("SOID", orderIDCombo.getSelectedItem().toString());
            params.put("SUPPLIER", supplierCombo.getSelectedItem().toString());
            params.put("OD", orderDateText.getText());
            params.put("OrderReceivedDate" , RecievedDatePicker.getDate().toString());
            JRTableModelDataSource ds = new JRTableModelDataSource(grnTable.getModel());

            ReportController.viewReport(params, "./src/dumbara/reports/grnReport.jrxml", ds);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void qtyTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyTextKeyReleased
        String volume = volumeText.getText();
        String qty = qtyText.getText();
        
        if(!volume.equals("")&& !qty.equals("")){
            addButton.setEnabled(true);
        }
    }//GEN-LAST:event_qtyTextKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewGRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewGRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewGRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewGRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewGRN dialog = new NewGRN(new javax.swing.JFrame(), false);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private String generateID() throws ClassNotFoundException, SQLException{
        String grnID=GoodRecievenoteController.getLastId();
        if(grnID==null){
            return "GRN0001";
        }else{
            int num=Integer.parseInt(grnID.substring(3));
            num++;
            if(num<10){
                return "GRN000"+num;
            }
            else if(num<100){
                return "GRN00"+num;
            }
            else if(num<1000){
                return "GRN0"+num;
            }else if(num<10000){
                return "GRN";
            }
            else{
                return null;
            }
        }
    }
        public String generateID1() throws ClassNotFoundException, SQLException{
        String id=EmptyBottleController.getLastID();
        if(id==null){
            return "BT01";
        }else{
            int num=Integer.parseInt(id.substring(2));
            num++;
            if(num<10){
                return "BT0"+num;
            }else{
                return "BT"+num;
            }
        }
    }
    private void fillSupplierCombo() {
        try {
            Supplier[] suppliers = SupplierController.viewSupplier();
            for (Supplier supplier : suppliers) {
                supplierCombo.addItem(supplier);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(NewGRN.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker RecievedDatePicker;
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTable grnTable;
    private javax.swing.JTextField grnText;
    private javax.swing.JTextField idText;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField orderDateText;
    private javax.swing.JComboBox orderIDCombo;
    private javax.swing.JTextField qtyText;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton resetText;
    private javax.swing.JComboBox supplierCombo;
    private javax.swing.JTable viewTable;
    private javax.swing.JTextField volumeText;
    // End of variables declaration//GEN-END:variables
}
