/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dumbara.view;

import dumabara.controller.AgencyController;
import dumabara.controller.AgencyOrderController;
import dumabara.controller.AgencyOrderDetailController;
import dumabara.controller.FilledBottleController;
import dumabara.controller.ReportController;
import dumabara.controller.SMSSender;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import dumbara.model.Agency;
import dumbara.model.AgencyOrder;
import dumbara.model.AgencyOrderDetail;
import dumbara.model.FilledBottle;
import dumbara.model.SMS;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;


/**
 *
 * @author chanu1993
 */
public class PlaceOrderAgency extends javax.swing.JFrame {

    /**
     * Creates new form PlaceOrderAgency
     */
    public PlaceOrderAgency() {
        initComponents();
        setLocationRelativeTo(null);
        String date = new SimpleDateFormat("yyyy/MM/dd").format(Calendar.getInstance().getTime());
        dateText.setText(date);
        try {
            FilledBottle[] filledBottles = FilledBottleController.viewFilledBottles();
            DefaultTableModel dtm = (DefaultTableModel) stockTable.getModel();
            for (FilledBottle filledBottle : filledBottles) {
                Object[] row = {filledBottle.getBottleID(), filledBottle.getBottleVolume(), filledBottle.getInStockQty(), filledBottle.getUnitPrice()};
                dtm.addRow(row);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PlaceOrderAgency.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            idText.setText(generateID());
            fillAgencyCombo();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PlaceOrderAgency.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            AgencyOrder[] agencyOrders=AgencyOrderController.getAllOrders();
            DefaultTableModel dtm = (DefaultTableModel) agencyOrderTable.getModel();
            for (AgencyOrder agencyOrder : agencyOrders) {
                Object[] rows={agencyOrder.getAgencyOrderID(),agencyOrder.getAgencyID(),agencyOrder.getDate()};
                dtm.addRow(rows);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PlaceOrderAgency.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jButton1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        agencyOrderTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        totText1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        dateText = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stockTable = new javax.swing.JTable();
        agencyCombo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderDetailLsitTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        reloadButton = new javax.swing.JButton();
        addtext = new javax.swing.JTextField();
        idText = new javax.swing.JTextField();
        printButton = new javax.swing.JButton();
        totText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel4.setBackground(java.awt.Color.white);

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 2));

        agencyOrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AgencyID", "AgencyOID", "Date"
            }
        ));
        agencyOrderTable.setRowHeight(25);
        agencyOrderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agencyOrderTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(agencyOrderTable);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("All Agency Orders");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Agency Order Details");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BottleID", "Qty", "UnitPrice", "TotalPrice"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        jLabel11.setText("Sub Total:");

        totText1.setEditable(false);
        totText1.setBackground(new java.awt.Color(153, 153, 255));
        totText1.setText("0");
        totText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totText1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(totText1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 153), 2, true));

        dateText.setBackground(new java.awt.Color(255, 204, 204));
        dateText.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        cancelButton.setBackground(new java.awt.Color(204, 204, 255));
        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel7.setText("Order Detail List");

        saveButton.setBackground(new java.awt.Color(204, 204, 255));
        saveButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveButton.setText("Save");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Place Agency Order");

        stockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Volume", "Available Qty", "UnitPrice"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        stockTable.setRowHeight(30);
        stockTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stockTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stockTable);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel4.setText("In Stock Detail");

        jLabel5.setText("Add to List");

        jLabel6.setText(">>>>");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Agency Order ID :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Agency ID :");

        orderDetailLsitTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Qty", "UnitPrice", "TotalPrice"
            }
        ));
        orderDetailLsitTable.setRowHeight(30);
        orderDetailLsitTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderDetailLsitTableMouseClicked(evt);
            }
        });
        orderDetailLsitTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                orderDetailLsitTablePropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(orderDetailLsitTable);

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jButton1.setText("Remove Row");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        reloadButton.setBackground(new java.awt.Color(204, 204, 255));
        reloadButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reloadButton.setText("Reset");
        reloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadButtonActionPerformed(evt);
            }
        });

        addtext.setEnabled(false);
        addtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtextActionPerformed(evt);
            }
        });
        addtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addtextFocusGained(evt);
            }
        });
        addtext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addtextKeyReleased(evt);
            }
        });

        idText.setEditable(false);
        idText.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        printButton.setBackground(new java.awt.Color(204, 204, 255));
        printButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printButton.setText("Print");
        printButton.setEnabled(false);
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        totText.setEditable(false);
        totText.setBackground(new java.awt.Color(153, 153, 255));
        totText.setText("0");
        totText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totTextActionPerformed(evt);
            }
        });

        jLabel10.setText("Sub Total:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(addtext, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel6))))
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(totText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(reloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(28, 28, 28)
                            .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jLabel1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(26, 26, 26)
                                    .addComponent(agencyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(agencyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(totText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stockTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockTableMouseClicked
        addtext.requestFocus();
        addtext.setEnabled(true);
    }//GEN-LAST:event_stockTableMouseClicked

    private void addtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addtextFocusGained
        addtext.selectAll();
    }//GEN-LAST:event_addtextFocusGained

    private void addtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtextActionPerformed
        int row = stockTable.getSelectedRow();
        String id = (String) stockTable.getModel().getValueAt(row, 0);
        String qty = addtext.getText();
        String unitPrice = (String) stockTable.getModel().getValueAt(row, 3);
        int tot;
        tot = Integer.parseInt(qty) * Integer.parseInt(unitPrice);
        String totalPrice = tot + "";
        DefaultTableModel dtm = (DefaultTableModel) orderDetailLsitTable.getModel();

        String qtyOnHand = (String) stockTable.getValueAt(row, 2).toString();
        boolean b=true;
        for (int i = 0; i < orderDetailLsitTable.getRowCount(); i++) {
            if(id.equals(orderDetailLsitTable.getModel().getValueAt(i, 0).toString())){
                JOptionPane.showMessageDialog(agencyCombo, "Item Already Exists");
                b=false;
            }
        }
        if (b == true) {
            if (Integer.parseInt(qty) < Integer.parseInt(qtyOnHand)) {
                Object[] rows = {id, qty, unitPrice, totalPrice};
                dtm.addRow(rows);
                stockTable.setValueAt(Integer.parseInt(qtyOnHand) - Integer.parseInt(qty), row, 2);

            } else {
                System.err.println("Invalid qty");
                JOptionPane.showMessageDialog(this, "Invalid Qty");
            }
        }
        //get the sub total....
        //totText.setText("0");
        double total1=Double.parseDouble(tot+"");
        double subTotal=Double.parseDouble(totText.getText())+total1;
        totText.setText(subTotal+"");
        
        saveButton.setEnabled(true);
        printButton.setEnabled(true);

    }//GEN-LAST:event_addtextActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        DefaultTableModel defaultTableModel=(DefaultTableModel) orderDetailLsitTable.getModel();
        int row=orderDetailLsitTable.getSelectedRow();
        
        double total=Double.parseDouble(totText.getText());
        double itemVal=Double.parseDouble(orderDetailLsitTable.getValueAt(row, 2).toString());
        double finale=total-itemVal;
        totText.setText(finale+"");
        
        
        defaultTableModel.removeRow(row);
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        
        if(!(orderDetailLsitTable.getRowCount()==0)){
            String agencyOrderID=idText.getText();
        String agencyID=agencyCombo.getSelectedItem().toString().split("-")[0];
        String date=dateText.getText();
        AgencyOrder agencyOrder=new AgencyOrder(agencyID, agencyOrderID, date);
        
        int rowCount=orderDetailLsitTable.getRowCount();
        
        AgencyOrderDetail[] agencyOrderDetail=new AgencyOrderDetail[rowCount];
        for (int i = 0; i < rowCount; i++) {
                 
                 String bottleID=(String) orderDetailLsitTable.getValueAt(i, 0);
                 String qty=(String) orderDetailLsitTable.getValueAt(i, 1);
                 String unitPrice=(String) orderDetailLsitTable.getValueAt(i, 2);
                 String totalPrice=(String) orderDetailLsitTable.getValueAt(i, 3);
                 
                 AgencyOrderDetail agencyOrderDetail1=new AgencyOrderDetail(agencyOrderID, bottleID, qty, unitPrice, totalPrice);
                 agencyOrderDetail[i]=agencyOrderDetail1;
        }
        try {
            int res=AgencyOrderController.addOrder(agencyOrder, agencyOrderDetail);
            if(res>0){
                JOptionPane.showMessageDialog(this, "Added");
            }else{
                JOptionPane.showMessageDialog(this, "Error");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PlaceOrderAgency.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            AgencyOrder[] agencyOrders=AgencyOrderController.getAllOrders();
            DefaultTableModel dtm = (DefaultTableModel) agencyOrderTable.getModel();
            dtm.setRowCount(0);
            for (AgencyOrder agencyOrder1 : agencyOrders) {
                Object[] rows={agencyOrder1.getAgencyOrderID(),agencyOrder1.getAgencyID(),agencyOrder1.getDate()};
                dtm.addRow(rows);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PlaceOrderAgency.class.getName()).log(Level.SEVERE, null, ex);
        }
       DefaultTableModel dtm = (DefaultTableModel) orderDetailLsitTable.getModel();
       dtm.setRowCount(0);
        }else{
            JOptionPane.showMessageDialog(agencyCombo, "No Data in Table");            
        }
          /////////////////////////////////////////////////////////
        List<SMS> list=new ArrayList<>();
        
        for (int i = 0; i < orderDetailLsitTable.getRowCount() ; i++) {
            String id=orderDetailLsitTable.getValueAt(i, 0).toString();
            String qty=orderDetailLsitTable.getValueAt(i, 1).toString();
            String unitPrice=orderDetailLsitTable.getValueAt(i, 2).toString();
            String totalPrice=orderDetailLsitTable.getValueAt(i, 3).toString();
            
            SMS sms=new SMS(id, qty, unitPrice, totalPrice);
            list.add(sms); 
        }
       
        
        String id=agencyCombo.getSelectedItem().toString();
        Agency agencys=null;
        try {
             agencys=AgencyController.viewAllAgencybyID(id);
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PlaceOrderAgency.class.getName()).log(Level.SEVERE, null, ex);
        }
        String contactNo=agencys.getContactNo();
        String port="COM7";
        boolean sendAuto = SMSSender.sendAuto(port, contactNo, list);
        if(sendAuto){
            JOptionPane.showMessageDialog(agencyCombo, "SMS Sent Completed....");
        }
        //
        DefaultTableModel dtm = (DefaultTableModel) orderDetailLsitTable.getModel();
        dtm.setRowCount(0);
        addtext.setText("");
        try {
            idText.setText(generateID());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PlaceOrderAgency.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void agencyOrderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agencyOrderTableMouseClicked
        int row=agencyOrderTable.getSelectedRow();
        String id=agencyOrderTable.getModel().getValueAt(row, 1).toString();
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        try {
            AgencyOrderDetail[] agencyOrderDetails=AgencyOrderDetailController.viewAll(id);
            dtm.setRowCount(0);
            for (AgencyOrderDetail agencyOrderDetail : agencyOrderDetails) {
                Object[] rows={agencyOrderDetail.getBottleID(),agencyOrderDetail.getQty(),agencyOrderDetail.getUnitPrice(),agencyOrderDetail.getTotalPrice()};
                dtm.addRow(rows);
            }
         
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(NewGRN.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //get the sub total of each selected order
        double total=0;
        
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            total+=Double.parseDouble(jTable1.getValueAt(i, 3).toString());
        }
        totText1.setText(total+"");
        
    }//GEN-LAST:event_agencyOrderTableMouseClicked

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        try {
            Map<String, Object> params = new HashMap<>();
            params.put("AOID", idText.getText());
            params.put("AID", agencyCombo.getSelectedItem().toString().split("-")[0]);
            params.put("DATE", dateText.getText());
            params.put("NAME", agencyCombo.getSelectedItem().toString().split("-")[1]);
            params.put("TOTAL", totText.getText());
            JRTableModelDataSource ds = new JRTableModelDataSource(orderDetailLsitTable.getModel());

            ReportController.viewReport(params, "./src/dumbara/reports/agencyOrderReport.jrxml", ds);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_printButtonActionPerformed

    private void reloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadButtonActionPerformed

        DefaultTableModel dtm = (DefaultTableModel) orderDetailLsitTable.getModel();
        dtm.setRowCount(0);
        addtext.setText("");
        try {
            idText.setText(generateID());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PlaceOrderAgency.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_reloadButtonActionPerformed

    private void totTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totTextActionPerformed
        int rows=orderDetailLsitTable.getRowCount();
        int row=orderDetailLsitTable.getSelectedRow();
        int total=0;
        for (int i = 0; i < rows; i++) {
            int value=Integer.parseInt(orderDetailLsitTable.getModel().getValueAt(i, 3).toString());
            total+=value;
        }
        totText.setText(total+"");
    }//GEN-LAST:event_totTextActionPerformed

    private void totText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totText1ActionPerformed

    private void orderDetailLsitTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderDetailLsitTableMouseClicked
        jButton1.setEnabled(true);
    }//GEN-LAST:event_orderDetailLsitTableMouseClicked

    private void orderDetailLsitTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_orderDetailLsitTablePropertyChange
        
    }//GEN-LAST:event_orderDetailLsitTablePropertyChange

    private void addtextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addtextKeyReleased
        String txt = addtext.getText();
        int caretPosition = addtext.getCaretPosition();
        if (!txt.matches("^[0-9]{0,10}$")) {
            addtext.setText(txt.substring(0, caretPosition - 1) + txt.substring(caretPosition));
            addtext.setCaretPosition(caretPosition - 1);
        }
    }//GEN-LAST:event_addtextKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderAgency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderAgency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderAgency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderAgency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PlaceOrderAgency().setVisible(true);
            }
        });
    }

    public String generateID() throws ClassNotFoundException, SQLException {
        String id = AgencyOrderController.getLastID();
        if (id == null) {
            return "AOID001";
        } else {
            int num = Integer.parseInt(id.toString().substring(4));
            num++;
            if (num < 10) {
                return "AOID00" + num;
            } else if (num < 100) {
                return "AOID0" + num;
            } else {
                return "AOID" + num;
            }
        }
    }

    private void fillAgencyCombo() {
        try {
            Agency[] agencys = AgencyController.viewAllAgency();
            for (Agency agency : agencys) {
                agencyCombo.addItem(agency);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PlaceOrderAgency.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addtext;
    private javax.swing.JComboBox agencyCombo;
    private javax.swing.JTable agencyOrderTable;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField dateText;
    private javax.swing.JTextField idText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable orderDetailLsitTable;
    private javax.swing.JButton printButton;
    private javax.swing.JButton reloadButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTable stockTable;
    private javax.swing.JTextField totText;
    private javax.swing.JTextField totText1;
    // End of variables declaration//GEN-END:variables
}
