/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dumbara.view;

import dumabara.controller.EmployeeController;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import dumbara.model.Employee;
import javax.swing.JOptionPane;

/**
 *
 * @author chanu1993
 */
public class SearchEmployee extends javax.swing.JFrame {
    
    ArrayList<Object[]> employeeList;

    /**
     * Creates new form SearchEmployee
     */
    public SearchEmployee() {
        initComponents();
        setLocationRelativeTo(this);
        try {
            Employee[] empList=EmployeeController.viewAllEmployee();
            DefaultTableModel dtm = (DefaultTableModel) empTable.getModel();
            dtm.setRowCount(0);
            for (Employee employee : empList) {
                Object rows[]={employee.getEmpID(),employee.getName(),employee.getAddress(),employee.getContactNo(),employee.getCivilStatus(),employee.getEmergencyCall()};
                dtm.addRow(rows);
            }
        } catch (SQLException | ClassNotFoundException | IOException ex) {
            Logger.getLogger(SearchEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        employeeList=new ArrayList<>();
        for(int i=0;i<empTable.getRowCount();i++){
            Object[] row={empTable.getValueAt(i, 0),empTable.getValueAt(i, 1),empTable.getValueAt(i, 2),empTable.getValueAt(i, 3),empTable.getValueAt(i, 4),empTable.getValueAt(i, 5),};
            employeeList.add(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        refreshText = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        empTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        updateText = new javax.swing.JButton();
        nameText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 2, true));

        refreshText.setBackground(new java.awt.Color(153, 153, 255));
        refreshText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        refreshText.setText("Refresh");
        refreshText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTextActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("EmpId :");

        empTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmpID", "Name", "Address", "ContactNo", "CivilStatus", "Emergency"
            }
        ));
        empTable.setRowHeight(25);
        jScrollPane1.setViewportView(empTable);

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setText("View Image");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Name :");

        cancelButton.setBackground(new java.awt.Color(255, 153, 153));
        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        updateText.setBackground(new java.awt.Color(153, 153, 255));
        updateText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        updateText.setText("Update");
        updateText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateTextMouseClicked(evt);
            }
        });
        updateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTextActionPerformed(evt);
            }
        });

        nameText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Search & Update");

        idText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idTextKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshText)
                .addGap(18, 18, 18)
                .addComponent(updateText)
                .addGap(18, 18, 18)
                .addComponent(cancelButton)
                .addGap(113, 113, 113))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextKeyReleased
        String name=nameText.getText();
        DefaultTableModel dtm = (DefaultTableModel) empTable.getModel();
        dtm.setRowCount(0);
        for (Object[] objects : employeeList) {
            if(objects[1].toString().contains(name)){
                dtm.addRow(objects);
            }
        }
    }//GEN-LAST:event_nameTextKeyReleased

    public void refresh(){
        try {
            Employee[] empList=EmployeeController.viewAllEmployee();
            DefaultTableModel dtm = (DefaultTableModel) empTable.getModel();
            dtm.setRowCount(0);
            for (Employee employee : empList) {
                Object rows[]={employee.getEmpID(),employee.getName(),employee.getAddress(),employee.getContactNo(),employee.getCivilStatus(),employee.getEmergencyCall()};
                dtm.addRow(rows);
            }
        } catch (SQLException | ClassNotFoundException | IOException ex) {
            Logger.getLogger(SearchEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void idTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextKeyReleased
        String id=idText.getText();
        DefaultTableModel dtm = (DefaultTableModel) empTable.getModel();
        dtm.setRowCount(0);
        for (Object[] objects : employeeList) {
            if(objects[0].toString().contains(id)){
                dtm.addRow(objects);
            }
        }
    }//GEN-LAST:event_idTextKeyReleased

    private void refreshTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTextActionPerformed
        try {
            Employee[] empList=EmployeeController.viewAllEmployee();
            DefaultTableModel dtm = (DefaultTableModel) empTable.getModel();
            dtm.setRowCount(0);
            for (Employee employee : empList) {
                Object rows[]={employee.getEmpID(),employee.getName(),employee.getAddress(),employee.getContactNo(),employee.getCivilStatus(),employee.getEmergencyCall()};
                dtm.addRow(rows);
            }
        } catch (SQLException | ClassNotFoundException | IOException ex) {
            Logger.getLogger(SearchEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refreshTextActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void updateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTextActionPerformed
        
    }//GEN-LAST:event_updateTextActionPerformed

    private void updateTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateTextMouseClicked
        if(empTable.getSelectedRowCount()==0){
            JOptionPane.showMessageDialog(rootPane, "Error");
        }else{
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        
        int row=empTable.getSelectedRow();
        String empID=(String) empTable.getModel().getValueAt(row, 0);
        String name=(String) empTable.getModel().getValueAt(row, 1);
        String address=(String) empTable.getModel().getValueAt(row, 2);
        String contactNo=(String) empTable.getModel().getValueAt(row, 3);
        String civilStatus=(String) empTable.getModel().getValueAt(row, 4);
        String emergency=(String) empTable.getModel().getValueAt(row, 5);
        
        Employee employee=new Employee(empID, name, address, contactNo, civilStatus, emergency);
        
        new UpdateEmployee(this, rootPaneCheckingEnabled, x-100, y-100,employee).setVisible(true);
        refresh();
        }

    }//GEN-LAST:event_updateTextMouseClicked

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        if (empTable.getSelectedRowCount()==0) {
            JOptionPane.showMessageDialog(rootPane, "Error");
        }else{
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        int row=empTable.getSelectedRow();
        String empID=(String) empTable.getModel().getValueAt(row, 0);
        new ViewImage(this, rootPaneCheckingEnabled,x-100,y-100,empID).setVisible(true);
        }
        
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTable empTable;
    private javax.swing.JTextField idText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameText;
    private javax.swing.JButton refreshText;
    private javax.swing.JButton updateText;
    // End of variables declaration//GEN-END:variables
}
