/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dumbara.view;

import dumabara.controller.LoanController;
import dumabara.controller.LoanSettleController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import dumbara.model.Loan;
import dumbara.model.LoanSettle;

/**
 *
 * @author chanu1993
 */
public class SettlePayment extends javax.swing.JDialog {

    Loan loan;

    /**
     * Creates new form SettlePayment
     */
    public SettlePayment(java.awt.Frame parent, boolean modal, int x, int y, Loan loan) {
        super(parent, modal);
        initComponents();
        this.loan = loan;
        System.out.println("-------------------------------------");
        setLocation(x, y);
        LoanSettleIDText.setText(fillLoanSettleID());
        System.out.println("-------------------------------------");
        System.out.println(loan.getLongAmount());
        loanAmountText.setText(loan.getLongAmount());

        paymentText.setText(loan.getMonthlyPayment());
        duePaymentText.setText(loan.getLongAmount());
        paymentText.requestFocus();
        String dPayment;
        System.out.println("-------------------------------------");
        try {
            dPayment = LoanSettleController.getLastSettleAmount(loan.getLoanID());
            if (dPayment != null) {
                duePaymentText.setText(dPayment);
            } else {
                String loanAmount = LoanController.getLoanAmount(loan.getLoanID());
                duePaymentText.setText(loanAmount);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SettlePayment.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        loanAmountText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        paymentText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        duePaymentText = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LoanSettleIDText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jButton1.setBackground(new java.awt.Color(239, 15, 23));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Settle Payment");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        loanAmountText.setEditable(false);
        loanAmountText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loanAmountTextFocusGained(evt);
            }
        });

        jLabel4.setText("Loan Amount :");

        paymentText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentTextActionPerformed(evt);
            }
        });
        paymentText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paymentTextFocusGained(evt);
            }
        });

        jLabel6.setText("Due Payment :");

        duePaymentText.setEditable(false);
        duePaymentText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duePaymentTextActionPerformed(evt);
            }
        });
        duePaymentText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                duePaymentTextFocusGained(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Payment :");

        jLabel2.setText("LoanSettleID :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(updateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(duePaymentText, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loanAmountText))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(paymentText))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(LoanSettleIDText)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoanSettleIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(loanAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(paymentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(duePaymentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(63, 63, 63)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void loanAmountTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loanAmountTextFocusGained

        loanAmountText.selectAll();
    }//GEN-LAST:event_loanAmountTextFocusGained

    private void paymentTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentTextFocusGained

        paymentText.selectAll();
    }//GEN-LAST:event_paymentTextFocusGained

    private void duePaymentTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_duePaymentTextFocusGained

        duePaymentText.selectAll();
    }//GEN-LAST:event_duePaymentTextFocusGained

    private void paymentTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentTextActionPerformed

    }//GEN-LAST:event_paymentTextActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        double duPayment = (Double.parseDouble(duePaymentText.getText())) - (Double.parseDouble(paymentText.getText()));
        duePaymentText.setText(duPayment + "");
        duePaymentText.requestFocus();
        String loanID = loan.getLoanID();
        String loanAmount = loanAmountText.getText();
        String payment = paymentText.getText();
        String duePayment = duePaymentText.getText();
        String loanSettleID = LoanSettleIDText.getText();

        LoanSettle loanSettle = new LoanSettle(loanSettleID, loanID, loanAmount, payment, duePayment);
        try {
            int res = LoanSettleController.addLoanSettle(loanSettle);

            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Added");
            } else {
                JOptionPane.showMessageDialog(this, "Error");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SettlePayment.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_updateButtonActionPerformed

    private void duePaymentTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duePaymentTextActionPerformed
        // TODO add your handling code here:
        updateButton.requestFocus();
    }//GEN-LAST:event_duePaymentTextActionPerformed

    private String fillLoanSettleID() {
        try {
            String lsID = LoanSettleController.getLastID();
            if (lsID == null) {
                return "LS0001";
            } else {
                int num = Integer.parseInt(lsID.substring(2));
                num++;
                if (num < 10) {
                    return "LS000" + num;
                } else if (num < 100) {
                    return "LS00" + num;
                } else if (num < 1000) {
                    return "LS0" + num;
                } else {
                    return "LS" + num;
                }

            }

        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(SettlePayment.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LoanSettleIDText;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField duePaymentText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField loanAmountText;
    private javax.swing.JTextField paymentText;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
