/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dumbara.view;

import dumabara.controller.LoanController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import dumbara.model.Loan;

/**
 *
 * @author chanu1993
 */
public class ViewLoan extends javax.swing.JFrame {
    
    ArrayList<Object[]> rowList;
    private  int x;
    private  int y;

    /**
     * Creates new form ViewLoan
     */
    public ViewLoan() {
        initComponents();
        setLocationRelativeTo(null);
        try {
            Loan[] loan=LoanController.viewLoan();
            DefaultTableModel dtm=(DefaultTableModel) loanTable.getModel();
            for (Loan loan1 : loan) {
                Object[] rows={loan1.getLoanID(),loan1.getEmpID(),loan1.getLongAmount(),loan1.getLoanTerm(),loan1.getInterestRate(),loan1.getMonthlyPayment(),loan1.getDueAmount()};
                dtm.addRow(rows);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewLoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        rowList=new ArrayList<>();
        for(int i=0;i<loanTable.getRowCount();i++){
            Object[] row={loanTable.getValueAt(i, 0),loanTable.getValueAt(i, 1),loanTable.getValueAt(i, 2),loanTable.getValueAt(i, 3),loanTable.getValueAt(i, 4),loanTable.getValueAt(i, 5)};
            rowList.add(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        loanIdText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        loanTable = new javax.swing.JTable();
        empIdText = new javax.swing.JTextField();
        removeLoan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        settleButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Manage Loans");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        loanIdText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loanIdTextFocusGained(evt);
            }
        });
        loanIdText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                loanIdTextKeyReleased(evt);
            }
        });

        loanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LoanID", "EmpID", "Amount", "LoanTerm", "InterestRate", "MonthlyPayment"
            }
        ));
        jScrollPane1.setViewportView(loanTable);

        empIdText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                empIdTextFocusGained(evt);
            }
        });
        empIdText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                empIdTextKeyReleased(evt);
            }
        });

        removeLoan.setText("Remove Loan");
        removeLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLoanActionPerformed(evt);
            }
        });

        jLabel2.setText("Loan ID :");

        jLabel3.setText("Emp ID :");

        settleButton.setText("Settle Payments");
        settleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settleButtonMouseClicked(evt);
            }
        });
        settleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settleButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Payment History");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loanIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(settleButton)
                        .addGap(31, 31, 31)
                        .addComponent(removeLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton3)
                        .addGap(0, 157, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(loanIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(empIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settleButton)
                    .addComponent(removeLoan)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loanIdTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loanIdTextKeyReleased
        String loanId=loanIdText.getText();
        DefaultTableModel dtm=(DefaultTableModel) loanTable.getModel();
        dtm.setRowCount(0);
        for(Object[] row:rowList){
            if(row[0].toString().contains(loanId)){
                dtm.addRow(row);
            }
        }
    }//GEN-LAST:event_loanIdTextKeyReleased

    private void empIdTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empIdTextKeyReleased
        String empId=empIdText.getText();
        DefaultTableModel dtm=(DefaultTableModel) loanTable.getModel();
        dtm.setRowCount(0);
        for (Object[] objects : rowList) {
            if(objects[1].toString().contains(empId)){
                dtm.addRow(objects);
            }
        }
        
    }//GEN-LAST:event_empIdTextKeyReleased

    private void settleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settleButtonActionPerformed
       
    }//GEN-LAST:event_settleButtonActionPerformed

    private void loanIdTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loanIdTextFocusGained
        // TODO add your handling code here:
        loanIdText.selectAll();
    }//GEN-LAST:event_loanIdTextFocusGained

    private void empIdTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empIdTextFocusGained
        // TODO add your handling code here:
        empIdText.selectAll();
    }//GEN-LAST:event_empIdTextFocusGained

    public void refresh(){
        try {
            Loan[] loan=LoanController.viewLoan();
            DefaultTableModel dtm=(DefaultTableModel) loanTable.getModel();
            dtm.setRowCount(0);
            for (Loan loan1 : loan) {
                Object[] rows={loan1.getLoanID(),loan1.getEmpID(),loan1.getLongAmount(),loan1.getLoanTerm(),loan1.getInterestRate(),loan1.getMonthlyPayment(),loan1.getDueAmount()};
                dtm.addRow(rows);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewLoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void settleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settleButtonMouseClicked
        x=evt.getXOnScreen();
        y=evt.getYOnScreen();
        
        int row=loanTable.getSelectedRow();
        String loanAmount=(String) loanTable.getModel().getValueAt(row, 2);
        String monthlyPayment=(String) loanTable.getModel().getValueAt(row, 5);
        String loanID=(String) loanTable.getValueAt(row, 0);
        
        Loan loan=new Loan(loanAmount,monthlyPayment,loanID);
        
        new SettlePayment(this, true,x-100,y-100,loan).setVisible(true);
    }//GEN-LAST:event_settleButtonMouseClicked

    private void removeLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeLoanActionPerformed
        int row=loanTable.getSelectedRow();
        String LoanID=(String) loanTable.getModel().getValueAt(row, 0);
        try {
            int res=LoanController.deleteLoan(LoanID);
            if(res>0){
                JOptionPane.showMessageDialog(this, "Deleted");
                refresh();
            }else{
                JOptionPane.showMessageDialog(this, "Error");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewLoan.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_removeLoanActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new PaymentHistory(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField empIdText;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField loanIdText;
    private javax.swing.JTable loanTable;
    private javax.swing.JButton removeLoan;
    private javax.swing.JButton settleButton;
    // End of variables declaration//GEN-END:variables
}
